<?php
return array(
	'BE' => array(
		'disable_exec_function' => '0',
		'explicitADmode' => 'explicitAllow',
		'fileCreateMask' => '0666',
		'folderCreateMask' => '2777',
		'installToolPassword' => '8709cca166af7faa09b7b0da8210fdbc',
		'loginSecurityLevel' => 'rsa',
		'versionNumberInFilename' => 'embed',
	),
	'DB' => array(
		'database' => 'local-012-709',
		'host' => 'localhost',
		'password' => 'ess:3',
		'username' => 'root',
	),
	'EXT' => array(
		'extConf' => array(
			'boxmodel' => 'a:12:{s:19:"enableDeveloperMode";s:1:"0";s:25:"enableDefaultPageTSconfig";s:1:"1";s:25:"enableDefaultUserTSconfig";s:1:"1";s:18:"enableMinimizedRTE";s:1:"1";s:18:"beCompressionLevel";s:1:"5";s:18:"feCompressionLevel";s:1:"5";s:24:"disableTsTemplateEditing";s:1:"1";s:15:"dontCompressCss";s:1:"0";s:14:"dontCompressJs";s:1:"0";s:18:"dontConcatenateCss";s:1:"0";s:17:"dontConcatenateJs";s:1:"0";s:28:"dontMoveJsFromHeaderToFooter";s:1:"0";}',
			'crawler' => 'a:15:{s:9:"sleepTime";s:4:"1000";s:16:"sleepAfterFinish";s:2:"10";s:11:"countInARun";s:3:"100";s:14:"purgeQueueDays";s:2:"14";s:12:"processLimit";s:1:"1";s:17:"processMaxRunTime";s:3:"300";s:14:"maxCompileUrls";s:5:"10000";s:12:"processDebug";s:1:"0";s:16:"crawlHiddenPages";s:1:"0";s:7:"phpPath";s:12:"/usr/bin/php";s:14:"enableTimeslot";s:1:"1";s:11:"logFileName";s:0:"";s:9:"follow30x";s:1:"0";s:18:"makeDirectRequests";s:1:"0";s:16:"frontendBasePath";s:1:"/";}',
			'formhandler' => 'a:0:{}',
			'indexed_search' => 'a:18:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"1";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"1";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
			'realurl' => 'a:5:{s:10:"configFile";s:0:"";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}s:3:"BE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}}',
			'simulatestatic' => 'a:0:{}',
			'static_info_tables' => 'a:1:{s:7:"charset";s:5:"utf-8";}',
			'templavoila' => 'a:2:{s:7:"enable.";a:3:{s:13:"oldPageModule";s:1:"0";s:19:"selectDataStructure";s:1:"0";s:15:"renderFCEHeader";s:1:"0";}s:9:"staticDS.";a:3:{s:6:"enable";s:1:"1";s:8:"path_fce";s:57:"typo3conf/ext/boxmodel/Resources/Private/Templavoila/fce/";s:9:"path_page";s:58:"typo3conf/ext/boxmodel/Resources/Private/Templavoila/page/";}}',
			'tq_seo' => 'a:4:{s:10:"enableBeta";s:1:"1";s:23:"enableIntegrationTTNews";s:1:"1";s:29:"sitemap_clearCachePossibility";s:1:"0";s:29:"sitemap_pageSitemapExpireDays";s:1:"0";}',
		),
		'extListArray' => array(
			'extbase',
			'css_styled_content',
			'info',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'rsaauth',
			'saltedpasswords',
			'scheduler',
			'fluid',
			'workspaces',
			'cshmanual',
			'simulatestatic',
			'opendocs',
			'static_info_tables',
			'recycler',
			'feedit',
			'adodb',
			'dbal',
			'templavoila',
			'crawler',
			'indexed_search',
			'tq_seo',
			'realurl',
			'boxmodel',
			'formhandler',
		),
		'extList_FE' => 'extbase,css_styled_content,version,install,rtehtmlarea,t3skin,felogin,form,rsaauth,saltedpasswords,fluid,workspaces,static_info_tables,feedit,templavoila,crawler,indexed_search,tq_seo,realurl,boxmodel',
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(),
		),
	),
	'FE' => array(
		'disableNoCacheParameter' => '1',
		'hidePagesIfNotTranslatedByDefault' => '1',
		'loginSecurityLevel' => 'rsa',
		'pageNotFound_handling' => 'USER_FUNCTION:typo3conf/ext/boxmodel/Classes/UserFunc/user_notfound.php:user_pageNotFound',
		'pageNotFound_handling_statheader' => 'HTTP/1.1 404 Not Found',
		'pageUnavailable_handling' => 'USER_FUNCTION:typo3conf/ext/boxmodel/Classes/UserFunc/user_notfound.php:user_pageNotFound',
		'versionNumberInFilename' => 'embed',
	),
	'GFX' => array(
		'gdlib_png' => '1',
		'im_combine_filename' => 'composite',
		'im_version_5' => 'im6',
		'jpg_quality' => '80',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\CompressionLevelUpdate' => 1,
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
		),
	),
	'SYS' => array(
		'compat_version' => '6.0',
		'encryptionKey' => 'c55c08155ee635c481e6ec4b5f481f562d64702d1de43daa1964e70156af825bf6de0b65bcd1fb691a83bbe097749984',
		'sitename' => 'Slim Boxmodel',
	),
);
?>